language: node_js
node_js:
 - "10.15.1"
before_install:
  - cd src
  - npm i -g npm@6.4.1
install:
  - npm install
cache: 
  - npm
script:
  - npm run test
notifications:
  slack: nyu-agile-software:4Ll9V7RPK8fkqf2dGDvWiEGt
